## visualization configuration file 

# output file path
#outputFilePath: "/home/galucia/antiLithium4/analysis/output/mc_visual.root"
outputFilePath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/mc_visual.root"
#studiesOutputFilePath: "/home/galucia/antiLithium4/analysis/output/mc_studies.root"
studiesOutputFilePath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/mc_studies.root"
outDirs: ["InvMass", "Pt", "PTPC", "Eta", "Phi", "DCA", "PID", "ClusterSize", "Efficiency", "Correlations"]

Sign: { name: "Sign",
        title: "Sign (Reconstructed); Sign; Counts",
        xVariable: "fSign",
        nXBins: 3,
        xMin: -1.5,
        xMax: 1.5,
        type: "TH1F",
        particle: ["He3", "Pr", "Li"],
        opt: 'reco',
        dir: None,
        }

MassMC: {  name: "MassMC",
      title: "Mass ; m (GeV/#it{c}); Counts",
      xVariable: "fMassMC",
      nXBins: 30,
      xMin: 3.75,
      xMax: 3.756,
      type: "TH1F",
      particle: ["Li"],
      opt: 'reco',
      dir: "InvMass",
      }

InvMass: {  name: "InvMass",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}); Counts",
            xVariable: "fMassInv",
            nXBins: 30,
            xMin: 3.745,
            xMax: 3.765,
            type: "TH1F",
            particle: ["Li"],
            opt: 'reco',
            dir: "InvMass",
            }

InvMassMC: {  name: "InvMassMC",
              title: "Invariant Mass MC; m (GeV/#it{c}); Counts",
              xVariable: "fMassInvMC",
              nXBins: 30,
              xMin: 3.75,
              xMax: 3.756,
              type: "TH1F",
              particle: ["Li"],
              opt: 'full',
              dir: "InvMass",
              }

Pt: { name: "Pt",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 100,
      xMin: -5,
      xMax: 5,
      type: "TH1F",
      particle: ["He3", "Pr", "Li"],
      opt: 'reco',
      dir: "Pt",
      }

PtMC: { name: "PtMC",
        title: "p_{T}^{true} Distribution (Generated); p_{T}^{true} (GeV/#it{c}); Counts",
        xVariable: "fSignedPtMC",
        selection: "",
        nXBins: 100,
        xMin: -5,
        xMax: 5,
        type: "TH1F",
        particle: ["He3", "Pr", "Li"],
        opt: 'full',
        dir: "Pt",
      }

PTPC: { name: "PTPC",
        title: "p_{TPC}^{reco} Distribution (fullerated); p_{T}^{reco} (GeV/#it{c}); Counts",
        xVariable: "fInnerPTPC",
        selection: "",
        nXBins: 100,
        xMin: 0,
        xMax: 10,
        type: "TH1F",
        #particle: ["He3", "Pr", "Li"],
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "PTPC",
      }

PMC: { name: "PMC",
        title: "p_{TPC}^{true} Distribution (Generated); p_{T}^{true} (GeV/#it{c}); Counts",
        xVariable: "fPMC",
        selection: "",
        nXBins: 100,
        xMin: 0,
        xMax: 10,
        type: "TH1F",
        #particle: ["He3", "Pr", "Li"],
        particle: ["He3", "Pr"],
        opt: 'full',
        dir: "PTPC",
      }

Eta: { name: "Eta",
        title: "#eta Distribution (Reconstructed); #eta; Counts",
        xVariable: "fEta",
        selection: "",
        nXBins: 100,
        xMin: -1,
        xMax: 1,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "Eta",
      }

Phi: { name: "Phi",
        title: "#phi Distribution (Reconstructed); #phi; Counts",
        xVariable: "fPhi",
        selection: "",
        nXBins: 100,
        xMin: -3.14,
        xMax: 3.14,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "Phi",
      }

DCAxy: { name: "DCAxy",
        title: "DCAxy Distribution (Reconstructed); DCAxy [cm]; Counts",
        xVariable: "fDCAxy",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "DCA",
      }

DCAz: { name: "DCAz",
        title: "DCAz Distribution (Reconstructed); DCAz [cm]; Counts",
        xVariable: "fDCAz",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "DCA",
      }




# cluster size

ClSizeITS: { name: "ClSizeITS",
             title: "Cluster Size (Reconstructed); Cluster Size; Counts",
             xVariable: "fClSizeITSMean",
             selection: "",
             nXBins: 20,
             xMin: 0,
             xMax: 20,
             type: "TH1F",
             particle: ["He3", "Pr"],
             opt: 'reco',
             dir: "ClusterSize",
             }

ClSizeITS0: { name: "ClSizeITS0",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS0",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS1: { name: "ClSizeITS1",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS1",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS2: { name: "ClSizeITS2",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS2",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS3: { name: "ClSizeITS3",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS3",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS4: { name: "ClSizeITS4",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS4",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS5: { name: "ClSizeITS5",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS5",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS6: { name: "ClSizeITS6", 
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS6",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeCosLam: { name: "clSizeCosLam",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITSCosLam",
                selection: "",
                nXBins: 100,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ITSclusterSizevsP: { name: "ITSclusterSizevsP",
                     title: "; signed #it{p}^{reco}_{TPC} (GeV/#it{c}); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
                     xVariable: "fSignedPt",
                     yVariable: "fClSizeITSCosLam",
                     nXBins: 500,
                     xMin: -5,
                     xMax: 5,
                     nYBins: 120,
                     yMin: 0,
                     yMax: 15,
                     type: "TH2F",
                     particle: ["He3", "Pr"],
                     opt: 'reco',
                     dir: "ClusterSize",
                   } 

# Correlation studies

DeltaEtaDeltaPhi: { name: "DeltaEtaDeltaPhi",
              title: "; #Delta#eta; #Delta#phi",
              xVariable: "fDeltaEta",
              yVariable: "fDeltaPhi",
              nXBins: 100,
              xMin: -0.5,
              xMax: 0.5,
              nYBins: 100,
              yMin: -0.5,
              yMax: 0.5,
              type: "TH2F",
              particle: [""],
              opt: 'reco',
              dir: "Correlations",
            }

DeltaEtaDeltaPhiMC: { name: "DeltaEtaDeltaPhiMC",
              title: "; #Delta#eta (generated); #Delta#phi (generated)",
              xVariable: "fDeltaEtaMC",
              yVariable: "fDeltaPhiMC",
              nXBins: 100,
              xMin: -0.5,
              xMax: 0.5,
              nYBins: 100,
              yMin: -0.5,
              yMax: 0.5,
              type: "TH2F",
              particle: [""],
              opt: 'reco',
              dir: "Correlations",
            }

Kstar: { name: "fKstar",
          title: "; K^{*}; Counts",
          xVariable: "fKstar",
          nXBins: 120,
          xMin: -0.6,
          xMax: 0.6,
          type: "TH1F",
          particle: [""],
          opt: 'reco',
          dir: "Correlations",
        } 


# resolution
ptRes: { name: "PtRes",
         title: "p_{T} Resolution; p_{T}^{reco}; (p_{T}^{true} - p_{T}^{reco})",
         xVariable: "fPt",
         yVariable: "fPtRes",
         nXBins: 25,
         xMin: 0,
         xMax: 5,
         nYBins: 100,
         yMin: -0.2,
         yMax: 0.2,
         type: "TH2F",
         opt: 'reco',
         particle: ["He3", "Pr", "Li"],
         dir: "Pt",
          }

ptResNotNorm: { name: "PtResNotNorm",
         title: "p_{T} Resolution; #it{p}_{T}^{true} (GeV/#it{c}); (#it{p}_{T}^{true} - #it{p}_{T}^{reco}) (GeV/#it{c})",
         xVariable: "fPtMC",
         yVariable: "fPtResNotNorm",
         nXBins: 25,
         xMin: 0,
         xMax: 5,
         nYBins: 1000,
         yMin: -0.5,
         yMax: 0.5,
         type: "TH2F",
         opt: 'reco',
         particle: ["He3", "Pr", "Li"],
         dir: "Pt",
          }

pTPCRes: { name: "PTPCRes",
         title: "p_{TPC} Resolution; p^{gen}; (p^{gen} - p_{TPC}^{reco}) / p^{gen}",
         xVariable: "fPMC",
         yVariable: "fPRes",
         nXBins: 100,
         xMin: 0,
         xMax: 10,
         nYBins: 100,
         yMin: -0.2,
         yMax: 0.2,
         type: "TH2F",
         opt: 'reco',
         #particle: ["He3", "Pr", "Li"],
         particle: ["He3", "Pr"],
         dir: "PTPC",
          }

# PID hp

PIDtrk: { name: "PIDtrk",
        title: "PID for tracking Distribution; PIDtrk; Counts",
        xVariable: "fPIDtrk",
        selection: "",
        nXBins: 17,
        xMin: 0,
        xMax: 17,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "PID",
      }

PIDhp:  { name: "PIDhp",
          title: "PID HP; PID for tracking; p_{T} (GeV/#it{c})",
          xVariable: "fPIDtrk",
          yVariable: "fPt",
          nXBins: 17,
          xMin: 0,
          xMax: 17,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "PID",
        }

NSigmaTPC: { name: "NSigmaTPC",
          title: "NSigmaTPC (Reconstructed); n#sigma_{TPC}; Counts",
          xVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -8,
          xMax: 8,
          type: "TH1F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "PID",
        } 

NSigmaTPCvsPt: { name: "NSigmaTPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "PID",
        } 

NSigmaTPCvsP: { name: "NSigmaTPCvsP",
          title: "NSigmaTPC (Reconstructed); signed #it{p}^{reco}_{TPC} (GeV/#it{c}); n#sigma_{TPC}",
          xVariable: "fSignedPTPC",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "PID",
        } 

ITSclusterSizevsNsigmaTPC: { name: "ITSclusterSizevsNsigmaTPC",
                             title: "; n#sigma_{TPC}; #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
                             xVariable: "fNSigmaTPC",
                             yVariable: "fClSizeITSCosLam",
                             nXBins: 100,
                             xMin: -5,
                             xMax: 5,
                             nYBins: 120,
                             yMin: 0,
                             yMax: 15,
                             type: "TH2F",
                             particle: ["He3", "Pr"],
                             opt: 'reco',
                             dir: "PID",
                        }
                   


# efficiency

efficiency: { name: "Efficiency",
                  title: "Efficiency; p_{T} (GeV/#it{c}); Efficiency",
                  numVariable: "fPt",
                  denVariable: "fPtMC",
                  nXBins: 50,
                  xMin: 0,
                  xMax: 10,
                  type: "TEfficiency",
                  particle: ["He3", "Pr", "Li"],
                  dir: "Efficiency",
              }


# Bethe Bloch

BetheBloch: { name: "dEdXvsP",
              title: "Bethe Bloch (Reconstructed); #beta#gamma; dE/dx [a.u.]",
              xVariable: "fBetaGamma",
              yVariable: "fSignalTPC",
              nXBins: 200,
              xMin: 0,
              xMax: 2,
              nYBins: 100,
              yMin: 0,
              yMax: 2000,
              type: "TH2F",
              particle: ["He3", "Pr"],
              opt: 'reco',
              dir: None,
            }
