## visualization configuration file 

# output file path
#studiesOutputFilePath: "/home/galucia/antiLithium4/analysis/output/Thin/event_mixing_studies.root"
studiesOutputFilePath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/studies.root"
outDirs: ["InvMass", "Kinematics", "TPC", "DCA", "PID", "ClusterSize", "Efficiency", "Correlations"]

InvMass: {  name: "InvMass",
            title: "Invariant Mass (Reconstructed); m [GeV/#it{c}]; Counts",
            xVariable: "fMassInv",
            nXBins: 100,
            xMin: 3.7,
            xMax: 3.9,
            type: "TH1F",
            particle: ["Li"],
            opt: 'reco',
            dir: "InvMass",
            }

Pt: { name: "Pt",
      title: "p_{T} Distribution (Reconstructed); p_{T} [GeV/#it{c}]; Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Pr", "Li"],
      opt: 'reco',
      dir: "Kinematics",
      }

PTPC: { name: "PTPC",
        title: "p_{TPC}^{reco} Distribution (Generated); p_{T}^{reco} [GeV/#it{c}]; Counts",
        xVariable: "fSignedPTPC",
        selection: "",
        nXBins: 200,
        xMin: -10,
        xMax: 10,
        type: "TH1F",
        #particle: ["He3", "Pr", "Li"],
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "TPC",
      }

Eta: { name: "Eta",
        title: "#eta Distribution (Reconstructed); #eta; Counts",
        xVariable: "fEta",
        selection: "",
        nXBins: 100,
        xMin: -1,
        xMax: 1,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "Kinematics",
      }

Phi: { name: "Phi",
        title: "#phi Distribution (Reconstructed); #phi; Counts",
        xVariable: "fPhi",
        selection: "",
        nXBins: 100,
        xMin: -3.14,
        xMax: 3.14,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "Kinematics",
      }

PtvsPhi: { name: "PtvsPhi",
          title: "; #phi; signed #it{p}^{reco}_{T} (GeV/#it{c});",
          xVariable: "fPhi",
          yVariable: "fSignedPt",
          nXBins: 100,
          xMin: -3.14,
          xMax: 3.14,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "Kinematics",
        } 

DCAxy: { name: "DCAxy",
        title: "DCAxy Distribution (Reconstructed); DCAxy [cm]; Counts",
        xVariable: "fDCAxy",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "DCA",
      }

DCAz: { name: "DCAz",
        title: "DCAz Distribution (Reconstructed); DCAz [cm]; Counts",
        xVariable: "fDCAz",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "DCA",
      }




# cluster size

ClSizeITS: { name: "ClSizeITS",
             title: "Cluster Size (Reconstructed); Cluster Size; Counts",
             xVariable: "fClSizeITSMean",
             selection: "",
             nXBins: 20,
             xMin: 0,
             xMax: 20,
             type: "TH1F",
             particle: ["He3", "Pr"],
             opt: 'reco',
             dir: "ClusterSize",
             }

ClSizeITS0: { name: "ClSizeITS0",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS0",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS1: { name: "ClSizeITS1",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS1",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS2: { name: "ClSizeITS2",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS2",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS3: { name: "ClSizeITS3",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS3",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS4: { name: "ClSizeITS4",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS4",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS5: { name: "ClSizeITS5",
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS5",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeITS6: { name: "ClSizeITS6", 
                title: "Cluster Size (Reconstructed); Cluster Size; Counts",
                xVariable: "fClSizeITS6",
                selection: "",
                nXBins: 20,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClSizeCosLam: { name: "ClSizeCosLam",
                title: "#LT ITS Cluster Size #GT #times #LT cos#lambda #GT (Reconstructed); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT; Counts",
                xVariable: "fClSizeITSCosLam",
                selection: "",
                nXBins: 100,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: 'reco',
                dir: "ClusterSize",
                }

ClusterSizevsP: { name: "ClusterSizevsP",
          title: "; signed #it{p}^{reco}_{T} (GeV/#it{c}); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fSignedPt",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "ClusterSize",
        } 

ClusterSizevsNSigmaTPC: { name: "ClusterSizevsNSigmaTPC",
          title: "; n#sigma_{TPC}; #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fNSigmaTPC",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "PID",
        } 

# PID hp

PIDtrk: { name: "PIDtrk",
        title: "PID for tracking Distribution; PIDtrk; Counts",
        xVariable: "fPIDtrk",
        selection: "",
        nXBins: 17,
        xMin: -0.5,
        xMax: 16.5,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: 'reco',
        dir: "PID",
      }

PIDhp:  { name: "PIDhp",
          title: "PID HP; PID for tracking; p_{T} [GeV/#it{c}]",
          xVariable: "fPIDtrk",
          yVariable: "fSignedPt",
          nXBins: 17,
          xMin: -0.5,
          xMax: 16.5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "PID",
        }

# TPC

NSigmaTPC: { name: "NSigmaTPC",
          title: "NSigmaTPC (Reconstructed); n#sigma_{TPC}; Counts",
          xVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -8,
          xMax: 8,
          type: "TH1F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "TPC",
        } 

NSigmaTPCvsPt: { name: "NSigmaTPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} [GeV/#it{c}]; n#sigma_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "TPC",
        } 

NSigmaTPCvsP: { name: "NSigmaTPCvsP",
          title: "NSigmaTPC (Reconstructed); signed #it{p}^{reco}_{TPC} [GeV/#it{c}]; n#sigma_{TPC}",
          xVariable: "fSignedPTPC",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "TPC",
        } 

chi2TPCvsPt: { name: "chi2TPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} [GeV/#it{c}]; #chi^2_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fChi2TPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: 0,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: 'reco',
          dir: "TPC",
        } 

# Bethe Bloch

BetheBlochP: { name: "dEdXvsP",
              title: "Bethe Bloch (Reconstructed); #it{p} [GeV/#it{c}]; dE/dx [a.u.]",
              xVariable: "fP",
              yVariable: "fSignalTPC",
              nXBins: 200,
              xMin: 0,
              xMax: 10,
              nYBins: 100,
              yMin: 0,
              yMax: 2000,
              type: "TH2F",
              particle: ["He3", "Pr"],
              opt: 'reco',
              dir: "TPC",
            }

BetheBloch: { name: "dEdXvsBetaGamma",
              title: "Bethe Bloch (Reconstructed); #beta#gamma; dE/dx [a.u.]",
              xVariable: "fBetaGamma",
              yVariable: "fSignalTPC",
              nXBins: 80,
              xMin: 0,
              xMax: 0.8,
              nYBins: 100,
              yMin: 0,
              yMax: 2000,
              type: "TH2F",
              particle: ["He3", "Pr"],
              opt: 'reco',
              dir: "TPC",
            }

# Correlation studies

DeltaEtaDeltaPhi: { name: "DeltaEtaDeltaPhi",
              title: "; #Delta#eta; #Delta#phi",
              xVariable: "fDeltaEta",
              yVariable: "fDeltaPhi",
              nXBins: 50,
              xMin: -0.5,
              xMax: 0.5,
              nYBins: 50,
              yMin: -0.5,
              yMax: 0.5,
              type: "TH2F",
              particle: [""],
              opt: 'reco',
              dir: "Correlations",
            }

Kstar: { name: "fKstar",
          title: "; K* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 200,
          xMin: 0.,
          xMax: 1.,
          type: "TH1F",
          particle: [""],
          opt: 'reco',
          dir: "Correlations",
        } 


# Self correlations

InvMassPt: { name: "InvMassPt",
              title: "Self correlations ; pt; m [GeV/#it{c}]",
              xVariable: "fSignedPtLi",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: -5,
              xMax: 5,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: 'reco',
              dir: "InvMass",
            }

InvMassTPCcls: { name: "InvMassTPCcls",
              title: "Self correlations ; n clusters TPC ^{3}He; m [GeV/#it{c}]",
              xVariable: "fNClsTPCHe3",
              yVariable: "fMassInvLi",
              nXBins: 80,
              xMin: 80,
              xMax: 160,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: 'reco',
              dir: "InvMass",
            }

InvMassTPCshared: { name: "InvMassTPCshared",
              title: "Self correlations ; n shared clusters TPC ^{3}He; m [GeV/#it{c}]",
              xVariable: "fSharedClustersHe3",
              yVariable: "fMassInvLi",
              nXBins: 150,
              xMin: 0,
              xMax: 150,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: 'reco',
              dir: "InvMass",
            }