# Same event
#input_data:   [ 
#                #'input/LHC23_PbPb_pass4_long_same_lsus_merged.root',
#                'input/LHC24ar_pass1_same_merged.root',
#                'input/LHC24as_pass1_same_merged.root'
#              ]
#tree_name:    'O2he3hadtable'
#mode:         'DF'
#output_file:  'output/same_event_old_24.root'

# Mixed event
input_data:   [
                #'/data/galucia/lithium_local/mixing/LHC23_PbPb_pass4_long_mixing_lsus.root',
                '/data/galucia/lithium_local/mixing/LHC24ar_pass1_mixing_lsus.root',
                '/data/galucia/lithium_local/mixing/LHC24as_pass1_mixing_lsus.root',
              ]
tree_name:    'MixedTree'
mode:         'tree'
output_file:  'output/mixed_event_old_24.root'

## MC
#input_data:   ['input/mc.root',
#                ]
#tree_name:    'O2he3hadtablemc'
#mode:         'DF'
#output_file:  'output/mc.root'

selections:     ['((fDeltaPhi/0.006)*(fDeltaPhi/0.006) + (fDeltaEta/0.012)*(fDeltaEta/0.012) > 1)',
                 '(std::abs(fEtaHe3) < 0.9)',
                 '((fPtHe3 < 2.5) || (fPIDtrkHe3 == 7))',
                 '((0.5 < fChi2TPCHe3) && (fChi2TPCHe3 < 4))',
                 #'((-1.5 < fNSigmaTPCHe3) && (fNSigmaTPCHe3 < 2.5))',
                 #'((-0.9 < fNSigmaTPCHe3) && (fNSigmaTPCHe3 < 1.9))', # 2023
                 '((-1.05 < fNSigmaTPCHe3) && (fNSigmaTPCHe3 < 1.75))', # 2024
                 '(std::abs(fDCAxyHe3) < 0.1)',
                 '(std::abs(fDCAzHe3) < 1.0)',
                 '(fClusterSizeCosLamHe3 > 4)',
                 '(fNSigmaITSHe3 > -1.5)',

                 '(std::abs(fEtaHad) < 0.9)',
                 '((0.5 < fChi2TPCHad) && (fChi2TPCHad < 4))',
                 '(std::abs(fNSigmaTPCHad) < 2)',
                 '((std::abs(fPtHad) < 0.8) || (std::abs(fNSigmaTOFHad) < 2))',
                 '(fNSigmaITSHad > -1.5)',
                ]
