## visualization configuration file 

# output file path
#studiesOutputFilePath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/studies.root"

# invariant mass configuration
#SEFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual_selectionsHe3.root"
#MEFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/event_mixing_visual_selectionsHe3.root"

# correlation configuration
#SEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual_selectionsPr.root"
#MEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/event_mixing_visual_selectionsPr.root"

# comparison studies
#SEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual_selectionsPr.root"
#MEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/event_mixing_visual_selectionsPr.root"

#figuresFolderPath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/figures/"



# output file path
studiesOutputFilePath: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/studies_US.root"

# invariant mass configuration
SEFileInvMass: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_US_selectionsPr.root"
MEFileInvMass: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/event_mixing_visual_selectionsPr.root"

# delta eta delta phi configuration
SEFileDeltaEtaDeltaPhi: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual.root"

# correlation configuration
SEFileCorrelation: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_US_selectionsPr.root"
MEFileCorrelation: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/event_mixing_visual_selectionsPr.root"

# tpc calibration configuration
InputFileTPCcalibration: "/data/galucia/lithium_local/mixing/LHC23zzh_pass4_small_mixing.root"
SEFileTPCcalibration: "/home/galucia/antiLithium4/analysis/output/LHC23zzh/event_mixing_visual_selectionsHe3.root"

# comparison studies
SEFileComparison: "/home/galucia/antiLithium4/analysis/output/LHC24/data_cross_check.root"
MEFileComparison: "/home/galucia/antiLithium4/analysis/output/LHC24/event_mixing_cross_check.root"

figuresFolderPath: "/home/galucia/antiLithium4/analysis/figures/"


comparisonVariables: ["Kinematics/PtHe3",
                      "Kinematics/PtPr",
                      "TPC/NSigmaTPCHe3",
                      "TPC/NSigmaTPCPr",
                      "DCA/DCAxyHe3",
                      "DCA/DCAzHe3",
                      "DCA/DCAxyPr",
                      "DCA/DCAzPr",]
