outDirs: ["QA", "InvMass", "Kinematics", "ITS", "TPC", "TOF", "DCA", "PID", "Centrality", "Efficiency", "Correlations", "SelfCorrelations"]

# QA
IsBkgUS: {  name: "IsBkgUS",
            title: "is bkg US (false/true); is bkg US (false/true); Counts",
            xVariable: "fIsBkgUSfloat",
            nXBins: 2,
            xMin: -0.5,
            xMax: 1.5,
            type: "TH1F",
            particle: [""],
            opt: "full",
            dir: "QA",
            }

# Kinematics

PtMatter: { name: "PtMatter",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Had", "Li"],
      opt: "matter",
      dir: "Kinematics",
      }

PtAnti: { name: "PtAnti",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Had", "Li"],
      opt: "antimatter",
      dir: "Kinematics",
      }

Eta: { name: "Eta",
        title: "#eta Distribution (Reconstructed); #eta; Counts",
        xVariable: "fEta",
        selection: "",
        nXBins: 100,
        xMin: -1,
        xMax: 1,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "Kinematics",
      }

Phi: { name: "Phi",
        title: "#phi Distribution (Reconstructed); #phi; Counts",
        xVariable: "fPhi",
        selection: "",
        nXBins: 100,
        xMin: -3.14,
        xMax: 3.14,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "Kinematics",
      }

DCAxy: { name: "DCAxy",
        title: "DCAxy Distribution (Reconstructed); DCAxy [cm]; Counts",
        xVariable: "fDCAxy",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "DCA",
      }

DCAz: { name: "DCAz",
        title: "DCAz Distribution (Reconstructed); DCAz [cm]; Counts",
        xVariable: "fDCAz",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "DCA",
      }


PtUS: { name: "PtUS",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Had"],
      opt: "unlike-sign",
      dir: "Kinematics",
      }

PtvsPhi: { name: "PtvsPhi",
          title: "; #phi; signed #it{p}^{reco}_{T} (GeV/#it{c});",
          xVariable: "fPhi",
          yVariable: "fSignedPt",
          nXBins: 100,
          xMin: -3.14,
          xMax: 3.14,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "Kinematics",
        } 

#PtMatterCent010: { name: "PtMatterCent010",
#      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
#      xVariable: "fSignedPt",
#      selection: "",
#      nXBins: 200,
#      xMin: -10,
#      xMax: 10,
#      type: "TH1F",
#      particle: ["Had"],
#      opt: "matter-cent0-10",
#      dir: "Kinematics",
#      }

# ITS

ClusterSizevsPSigned: { name: "ClusterSizevsPSigned",
          title: "; signed #it{p}^{reco}_{T} (GeV/#it{c}); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fSignedPt",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "ITS",
        }

NSigmaITSvsPt: { name: "NSigmaITSvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{ITS}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaITS",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "ITS",
        } 

ClSizeITS: { name: "ClSizeITS",
             title: "Cluster Size (Reconstructed); Cluster Size; Counts",
             xVariable: "fClSizeITSMean",
             selection: "",
             nXBins: 20,
             xMin: 0,
             xMax: 20,
             type: "TH1F",
             particle: ["He3", "Had"],
             opt: "antimatter",
             dir: "ITS",
             }

ClSizeCosLam: { name: "ClSizeCosLam",
                title: "#LT ITS Cluster Size #GT #times #LT cos#lambda #GT (Reconstructed); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT; Counts",
                xVariable: "fClSizeITSCosLam",
                selection: "",
                nXBins: 100,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Had"],
                opt: "antimatter",
                dir: "ITS",
                }

ClusterSizevsNSigmaTPC: { name: "ClusterSizevsNSigmaTPC",
          title: "; n#sigma_{TPC}; #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fNSigmaTPC",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "ITS",
        } 

# PID hp

PIDtrk: { name: "PIDtrk",
        title: "PID for tracking Distribution; PIDtrk; Counts",
        xVariable: "fPIDtrk",
        selection: "",
        nXBins: 17,
        xMin: -0.5,
        xMax: 16.5,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "PID",
      }

PIDhp:  { name: "PIDhp",
          title: "PID HP; PID for tracking; p_{T} (GeV/#it{c})",
          xVariable: "fPIDtrk",
          yVariable: "fSignedPt",
          nXBins: 17,
          xMin: -0.5,
          xMax: 16.5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "PID",
        }

# TPC

NSigmaTPCvsPt: { name: "NSigmaTPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "TPC",
        } 

BetheBloch: { name: "dEdXvsBetaGamma",
              title: "Bethe Bloch (Reconstructed); #beta#gamma; dE/dx [a.u.]",
              xVariable: "fBetaGamma",
              yVariable: "fSignalTPC",
              nXBins: 80,
              xMin: 0,
              xMax: 4,
              nYBins: 750,
              yMin: 0,
              yMax: 3000,
              type: "TH2F",
              particle: ["He3", "Had"],
              opt: "full",
              dir: "TPC",
            }

NSigmaTPCvsPt: { name: "NSigmaTPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "TPC",
        } 

chi2TPCvsPt: { name: "chi2TPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); #chi^2_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fChi2TPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: 0,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "TPC",
        } 

# TOF

NSigmaTOFvsPt: { name: "NSigmaTOFvsPt",
          title: "NSigmaTOF (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TOF}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTOF",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: -10,
          yMax: 10,
          type: "TH2F",
          particle: ["Had"],
          opt: "antimatter",
          dir: "TOF",
        }

TOFmassvsPtPr: { name: "TOFmassvsPtPr",
          title: "TOF mass (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); m_{TOF} (GeV/#it{c}^{2})",
          xVariable: "fSignedPtHad",
          yVariable: "fMassTOFHad",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: 0,
          yMax: 2,
          type: "TH2F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

NSigmaTOFvsPt: { name: "NSigmaTOFvsPt",
          title: "NSigmaTOF (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TOF}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTOF",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: -10,
          yMax: 10,
          type: "TH2F",
          particle: ["Had"],
          opt: "antimatter",
          dir: "TOF",
        }

TOFmassHe3: { name: "TOFmassHe3",
          title: "TOF mass (Reconstructed); m_{TOF} (GeV/#it{c}^{2}); Counts",
          xVariable: "fMassTOFHe3",
          nXBins: 200,
          xMin: 2,
          xMax: 4,
          type: "TH1F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

TOFmassvsPtHe3: { name: "TOFmassvsPtHe3",
          title: "TOF mass (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); m_{TOF} (GeV/#it{c}^{2})",
          xVariable: "fSignedPtHe3",
          yVariable: "fMassTOFHe3",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: 2,
          yMax: 4,
          type: "TH2F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

# Centrality

CentralityFT0C: { name: "CentralityFT0C",
      title: "; Centrality FT0C (%); Counts",
      xVariable: "fCentralityFT0C",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 100,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

MultiplicityFT0C: { name: "MultiplicityFT0C",
      title: "; Multiplicity FT0C; Counts",
      xVariable: "fMultiplicityFT0C",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 70000,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

CentralityFT0C: { name: "CentralityFT0C",
      title: "; Centrality FT0C (%); Counts",
      xVariable: "fCentralityFT0C",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 100,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

MultiplicityFT0C: { name: "MultiplicityFT0C",
      title: "; Multiplicity FT0C; Counts",
      xVariable: "fMultiplicityFT0C",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 70000,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

Multiplicity: { name: "Multiplicity",
      title: "; Multiplicity ; Counts",
      xVariable: "fMultiplicity",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 7000,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

CentralityMultiplicity: { name: "CentralityMultiplicity",
              title: " ; Centrality FT0C (%); Multiplicity FT0C",
              xVariable: "fCentralityFT0C",
              yVariable: "fMultiplicityFT0C",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 100,
              yMin: 0,
              yMax: 70000,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "Centrality",
            }

#CentralityFT0CMatter: { name: "CentralityFT0CMatter",
#      title: "; Centrality FT0C (%); Counts",
#      xVariable: "fCentralityFT0C",
#      selection: "",
#      nXBins: 100,
#      xMin: 0,
#      xMax: 100,
#      type: "TH1F",
#      particle: [""],
#      opt: "matter-cent0-10",
#      dir: "Centrality",
#      }

# Correlation studies

DeltaEtaDeltaPhi: { name: "DeltaEtaDeltaPhi",
              title: "; #Delta#eta; #Delta#phi",
              xVariable: "fDeltaEta",
              yVariable: "fDeltaPhi",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 50,
              yMin: -0.15,
              yMax: 0.15,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "Correlations",
            }

KstarLS: { name: "fKstarLS",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "like-sign",
          dir: "Correlations",
        }

InvMassvsKstar: { name: "InvMassvsKstar",
          title: "; #it{k}* (GeV/#it{c}); m (GeV/#it{c}^{2})",
          xVariable: "fKstar",
          yVariable: "fMassInvLi",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          nYBins: 300,
          yMin: 3.747,
          yMax: 4.047,
          type: "TH2F",
          particle: [""],
          opt: "antimatter",
          dir: "Correlations",
        }

KstarPtHe: { name: "KstarPtHe",
          title: "; #it{p}_{T} (^{3}He) (GeV/#it{c}); #it{k}* (GeV/#it{c});",
          xVariable: "fPtHe3",
          yVariable: "fKstar",
          nXBins: 200,
          xMin: -10,
          xMax: 10,
          nYBins: 400,
          yMin: 0.,
          yMax: 2.,
          type: "TH2F",
          particle: [""],
          opt: "full",
          dir: "Correlations",
        }


# Self correlations

InvMassTPCcls: { name: "InvMassTPCcls",
              title: "Self correlations ; n clusters TPC ^{3}He; m (GeV/#it{c})",
              xVariable: "fNClsTPCHe3",
              yVariable: "fMassInvLi",
              nXBins: 80,
              xMin: 80,
              xMax: 160,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

InvMassTPCshared: { name: "InvMassTPCshared",
              title: "Self correlations ; n shared clusters TPC ^{3}He; m (GeV/#it{c})",
              xVariable: "fSharedClustersHe3",
              yVariable: "fMassInvLi",
              nXBins: 150,
              xMin: 0,
              xMax: 150,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaPhiHe3: { name: "TPCsharedDeltaPhiHe3",
              title: "Self correlations ; #Delta#phi; n shared clusters TPC;",
              xVariable: "fDeltaPhi",
              yVariable: "fSharedClustersHe3",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaEtaHe3: { name: "TPCsharedDeltaEtaHe3",
              title: "Self correlations ; #Delta#eta; n shared clusters TPC ^{3}He;",
              xVariable: "fDeltaEta",
              yVariable: "fSharedClustersHe3",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaPhiPr: { name: "TPCsharedDeltaPhiPr",
              title: "Self correlations ; #Delta#phi; n shared clusters TPC;",
              xVariable: "fDeltaPhi",
              yVariable: "fSharedClustersHad",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaEtaPr: { name: "TPCsharedDeltaEtaPr",
              title: "Self correlations ; #Delta#eta; n shared clusters TPC ^{3}He;",
              xVariable: "fDeltaEta",
              yVariable: "fSharedClustersHad",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedPt: { name: "TPCsharedPt",
              title: "Self correlations ; #it{p}_{T} (GeV/#it{c}); n shared clusters TPC ^{3}He;",
              xVariable: "fSignedPt",
              yVariable: "fSharedClusters",
              nXBins: 200,
              xMin: -10,
              xMax: 10,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: ["He3", "Had"],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

# Checks

TrackID: { name: "fTrackID",
          title: "; trackID; Counts",
          xVariable: "fTrackID",
          nXBins: 600001,
          xMin: -0.5,
          xMax: 600000.5,
          type: "TH1F",
          particle: ["Had", "He3"],
          opt: "antimatter",
          dir: "PID",
        } 
