outDirs: ["InvMass", "Kinematics", "TPC", "TOF", "DCA", "PID", "ClusterSize", "Efficiency", "Correlations", "SelfCorrelations"]

InvMassMatter: {  name: "InvMassMatter",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            xMax: 4.047,
            type: "TH1F",
            particle: ["Li"],
            opt: "matter",
            dir: "InvMass",
            }

InvMassAnti: {  name: "InvMassAnti",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            xMax: 4.047,
            type: "TH1F",
            particle: ["Li"],
            opt: "antimatter",
            dir: "InvMass",
            }

InvMassLS: {  name: "InvMassLS",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            xMax: 4.047,
            type: "TH1F",
            particle: ["Li"],
            opt: "like-sign",
            dir: "InvMass",
            }

InvMassUS: {  name: "InvMassUS",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            xMax: 4.047,
            type: "TH1F",
            particle: ["Li"],
            opt: "unlike-sign",
            dir: "InvMass",
            }

PtMatter: { name: "PtMatter",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Pr", "Li"],
      opt: "matter",
      dir: "Kinematics",
      }

PtAnti: { name: "PtAnti",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Pr", "Li"],
      opt: "antimatter",
      dir: "Kinematics",
      }

Eta: { name: "Eta",
        title: "#eta Distribution (Reconstructed); #eta; Counts",
        xVariable: "fEta",
        selection: "",
        nXBins: 100,
        xMin: -1,
        xMax: 1,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: "antimatter",
        dir: "Kinematics",
      }

Phi: { name: "Phi",
        title: "#phi Distribution (Reconstructed); #phi; Counts",
        xVariable: "fPhi",
        selection: "",
        nXBins: 100,
        xMin: -3.14,
        xMax: 3.14,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: "antimatter",
        dir: "Kinematics",
      }

PtvsPhi: { name: "PtvsPhi",
          title: "; #phi; signed #it{p}^{reco}_{T} (GeV/#it{c});",
          xVariable: "fPhi",
          yVariable: "fSignedPt",
          nXBins: 100,
          xMin: -3.14,
          xMax: 3.14,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "Kinematics",
        } 

DCAxy: { name: "DCAxy",
        title: "DCAxy Distribution (Reconstructed); DCAxy [cm]; Counts",
        xVariable: "fDCAxy",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: "antimatter",
        dir: "DCA",
      }

DCAz: { name: "DCAz",
        title: "DCAz Distribution (Reconstructed); DCAz [cm]; Counts",
        xVariable: "fDCAz",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: "antimatter",
        dir: "DCA",
      }


# cluster size

ClSizeITS: { name: "ClSizeITS",
             title: "Cluster Size (Reconstructed); Cluster Size; Counts",
             xVariable: "fClSizeITSMean",
             selection: "",
             nXBins: 20,
             xMin: 0,
             xMax: 20,
             type: "TH1F",
             particle: ["He3", "Pr"],
             opt: "antimatter",
             dir: "ClusterSize",
             }

ClSizeCosLam: { name: "ClSizeCosLam",
                title: "#LT ITS Cluster Size #GT #times #LT cos#lambda #GT (Reconstructed); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT; Counts",
                xVariable: "fClSizeITSCosLam",
                selection: "",
                nXBins: 100,
                xMin: 0,
                xMax: 20,
                type: "TH1F",
                particle: ["He3", "Pr"],
                opt: "antimatter",
                dir: "ClusterSize",
                }

ClusterSizevsPSigned: { name: "ClusterSizevsPSigned",
          title: "; signed #it{p}^{reco}_{T} (GeV/#it{c}); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fSignedPt",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "ClusterSize",
        }

ClusterSizevsP: { name: "ClusterSizevsP",
          title: "; #it{p}^{reco}_{T} (GeV/#it{c}); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fPt",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: 0,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "ClusterSize",
        } 

ClusterSizevsNSigmaTPC: { name: "ClusterSizevsNSigmaTPC",
          title: "; n#sigma_{TPC}; #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fNSigmaTPC",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "ClusterSize",
        } 

NSigmaITSvsPt: { name: "NSigmaITSvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{ITS}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaITS",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "ClusterSize",
        } 

# PID hp

PIDtrk: { name: "PIDtrk",
        title: "PID for tracking Distribution; PIDtrk; Counts",
        xVariable: "fPIDtrk",
        selection: "",
        nXBins: 17,
        xMin: -0.5,
        xMax: 16.5,
        type: "TH1F",
        particle: ["He3", "Pr"],
        opt: "antimatter",
        dir: "PID",
      }

PIDhp:  { name: "PIDhp",
          title: "PID HP; PID for tracking; p_{T} (GeV/#it{c})",
          xVariable: "fPIDtrk",
          yVariable: "fSignedPt",
          nXBins: 17,
          xMin: -0.5,
          xMax: 16.5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "PID",
        }

# TPC

BetheBlochP: { name: "dEdXvsP",
              title: "Bethe Bloch (Reconstructed); #it{p} (GeV/#it{c}); dE/dx [a.u.]",
              xVariable: "fP",
              yVariable: "fSignalTPC",
              nXBins: 200,
              xMin: 0,
              xMax: 10,
              nYBins: 750,
              yMin: 0,
              yMax: 3000,
              type: "TH2F",
              particle: ["He3", "Pr"],
              opt: "full",
              dir: "TPC",
            }

BetheBloch: { name: "dEdXvsBetaGamma",
              title: "Bethe Bloch (Reconstructed); #beta#gamma; dE/dx [a.u.]",
              xVariable: "fBetaGamma",
              yVariable: "fSignalTPC",
              nXBins: 80,
              xMin: 0,
              xMax: 4,
              nYBins: 750,
              yMin: 0,
              yMax: 3000,
              type: "TH2F",
              particle: ["He3", "Pr"],
              opt: "full",
              dir: "TPC",
            }

NSigmaTPC: { name: "NSigmaTPC",
          title: "NSigmaTPC (Reconstructed); n#sigma_{TPC}; Counts",
          xVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -8,
          xMax: 8,
          type: "TH1F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "TPC",
        } 

NSigmaTPCvsPt: { name: "NSigmaTPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "TPC",
        } 

chi2TPCvsPt: { name: "chi2TPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); #chi^2_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fChi2TPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: 0,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Pr"],
          opt: "antimatter",
          dir: "TPC",
        } 

# TOF

TOFmassPr: { name: "TOFmassPr",
          title: "TOF mass (Reconstructed); m_{TOF} (GeV/#it{c}^{2}); Counts",
          xVariable: "fMassTOFPr",
          nXBins: 200,
          xMin: 0,
          xMax: 2,
          type: "TH1F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

TOFmassvsPtPr: { name: "TOFmassvsPtPr",
          title: "TOF mass (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); m_{TOF} (GeV/#it{c}^{2})",
          xVariable: "fSignedPtPr",
          yVariable: "fMassTOFPr",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: 0,
          yMax: 2,
          type: "TH2F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

NSigmaTOFvsPt: { name: "NSigmaTOFvsPt",
          title: "NSigmaTOF (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TOF}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTOF",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: -10,
          yMax: 10,
          type: "TH2F",
          particle: ["Pr"],
          opt: "antimatter",
          dir: "TOF",
        }

TOFmassHe3: { name: "TOFmassHe3",
          title: "TOF mass (Reconstructed); m_{TOF} (GeV/#it{c}^{2}); Counts",
          xVariable: "fMassTOFHe3",
          nXBins: 200,
          xMin: 2,
          xMax: 4,
          type: "TH1F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

TOFmassvsPtHe3: { name: "TOFmassvsPtHe3",
          title: "TOF mass (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); m_{TOF} (GeV/#it{c}^{2})",
          xVariable: "fSignedPtHe3",
          yVariable: "fMassTOFHe3",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: 2,
          yMax: 4,
          type: "TH2F",
          particle: [""],
          opt: "antimatter",
          dir: "TOF",
        } 

# Correlation studies

DeltaEtaDeltaPhi: { name: "DeltaEtaDeltaPhi",
              title: "; #Delta#eta; #Delta#phi",
              xVariable: "fDeltaEta",
              yVariable: "fDeltaPhi",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 50,
              yMin: -0.15,
              yMax: 0.15,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "Correlations",
            }

KstarAnti: { name: "fKstarAnti",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "antimatter",
          dir: "Correlations",
        }

KstarMatter: { name: "fKstarMatter",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "matter",
          dir: "Correlations",
        }

KstarUS: { name: "fKstarUS",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "unlike-sign",
          dir: "Correlations",
        }

KstarLS: { name: "fKstarLS",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "like-sign",
          dir: "Correlations",
        }

InvMassvsKstar: { name: "InvMassvsKstar",
          title: "; #it{k}* (GeV/#it{c}); m (GeV/#it{c}^{2})",
          xVariable: "fKstar",
          yVariable: "fMassInvLi",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          nYBins: 300,
          yMin: 3.747,
          yMax: 4.047,
          type: "TH2F",
          particle: [""],
          opt: "antimatter",
          dir: "Correlations",
        }


# Self correlations

InvMassPt: { name: "InvMassPt",
              title: "Self correlations ; pt; m (GeV/#it{c})",
              xVariable: "fSignedPtLi",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: -5,
              xMax: 5,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassTPCcls: { name: "InvMassTPCcls",
              title: "Self correlations ; n clusters TPC ^{3}He; m (GeV/#it{c})",
              xVariable: "fNClsTPCHe3",
              yVariable: "fMassInvLi",
              nXBins: 80,
              xMin: 80,
              xMax: 160,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

InvMassTPCshared: { name: "InvMassTPCshared",
              title: "Self correlations ; n shared clusters TPC ^{3}He; m (GeV/#it{c})",
              xVariable: "fSharedClustersHe3",
              yVariable: "fMassInvLi",
              nXBins: 150,
              xMin: 0,
              xMax: 150,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaPhiHe3: { name: "TPCsharedDeltaPhiHe3",
              title: "Self correlations ; #Delta#phi; n shared clusters TPC;",
              xVariable: "fDeltaPhi",
              yVariable: "fSharedClustersHe3",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaEtaHe3: { name: "TPCsharedDeltaEtaHe3",
              title: "Self correlations ; #Delta#eta; n shared clusters TPC ^{3}He;",
              xVariable: "fDeltaEta",
              yVariable: "fSharedClustersHe3",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaPhiPr: { name: "TPCsharedDeltaPhiPr",
              title: "Self correlations ; #Delta#phi; n shared clusters TPC;",
              xVariable: "fDeltaPhi",
              yVariable: "fSharedClustersPr",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedDeltaEtaPr: { name: "TPCsharedDeltaEtaPr",
              title: "Self correlations ; #Delta#eta; n shared clusters TPC ^{3}He;",
              xVariable: "fDeltaEta",
              yVariable: "fSharedClustersPr",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

TPCsharedPt: { name: "TPCsharedPt",
              title: "Self correlations ; #it{p}_{T} (GeV/#it{c}); n shared clusters TPC ^{3}He;",
              xVariable: "fSignedPt",
              yVariable: "fSharedClusters",
              nXBins: 200,
              xMin: -10,
              xMax: 10,
              nYBins: 150,
              yMin: 0,
              yMax: 150,
              type: "TH2F",
              particle: ["He3", "Pr"],
              opt: "antimatter",
              dir: "SelfCorrelations",
            }

# Checks

TrackID: { name: "fTrackID",
          title: "; trackID; Counts",
          xVariable: "fTrackID",
          nXBins: 600001,
          xMin: -0.5,
          xMax: 600000.5,
          type: "TH1F",
          particle: ["Pr", "He3"],
          opt: "antimatter",
          dir: "PID",
        } 
