#inFilePath: [ '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24af_pass1_skimmed_same.root',
#             '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24ag_pass1_skimmed_same.root',
#             '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24aj_pass1_skimmed_same.root',
#             #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24al_pass1_skimmed_same.root',
#             #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC23_pass4_skimmed_same.root'
#             ]
#outFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual.root'
#visualFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_visual.yml'

inFilePath: [ #'/data/galucia/lithium_local/same/LHC24af_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24ag_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24aj_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24al_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC23_pass4_skimmed_same.root',
              '/data/galucia/lithium_local/same/LHC23zzh_pass4_small_same.root',
              #'/home/galucia/antiLithium4/task/MCWorkflowAnalysis/LHC24af_same.root'
             ]

outFilePath: #'/home/galucia/antiLithium4/analysis/output/LHC24/data_visual.root'
             '/home/galucia/antiLithium4/analysis/output/LHC23zzh/data_visual.root'
             #'/home/galucia/antiLithium4/analysis/output/LHC24/data_cross_check.root'
visualFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_visual.yml'

antimatterOnly: True