#inFilePath: [ '/Users/glucia/Projects/ALICE/data/lithium/MC/LHC25a4.root',
#             ]
#outFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/MC/data_visual.root'
#outQaFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/MC/qa_us.root'
#visualFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_visual.yml'
#qaFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_qa.yml'

inFilePath: [ '/data/galucia/lithium_local/MC/LHC25a4.root',
             ]

outFilePath: '/home/galucia/antiLithium4/analysis/output/MC/data_visual.root'
outQaFilePath: '/home/galucia/antiLithium4/analysis/output/MC/qa.root'

visualFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_visual.yml'
qaFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_qa.yml'

treeNames: [ 'O2he3hadtable', 'O2he3hadmult' ]
#treeNames: [ 'fTreeLRC' ]
folderName: 'DF*'
antimatterOnly: True