## visualization configuration file 

# output file path
studiesOutputFilePath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/studies_corrected.root"

# invariant mass configuration
SEFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/data_visual_corrected_selectionsPr.root"
MEFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/event_mixing_visual_corrected_selectionsPr.root"
CorrectionFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/CATS/CATS.root"

# correlation configuration
SEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/data_visual_corrected_selectionsPr.root"
MEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/event_mixing_visual_corrected_selectionsPr.root"
GenuineFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/CATS/CATS.root"
GenuineNameCorrelation: "hHe3_p_Coul_CF_LS"
Centralities: 
  CentralityBinEdges: [0, 10, 30, 50]

# comparison studies
#SEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual_selectionsPr.root"
#MEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/event_mixing_visual_selectionsPr.root"

figuresFolderPath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/figures/"



## output file path
#studiesOutputFilePath: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/studies_grid.root"
#
## invariant mass configuration
#SEFileInvMass: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_selectionsPr.root"
#MEFileInvMass: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/event_mixing_visual_grid_LS_selectionsPr.root"
#CorrectionFileInvMass: "/home/galucia/antiLithium4/analysis/output/CATS/CATS.root"
#
## delta eta delta phi configuration
#SEFileDeltaEtaDeltaPhi: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual.root"
#
## correlation configuration
#SEFileCorrelation: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_selectionsPr.root"
#MEFileCorrelation: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/event_mixing_visual_grid_LS_selectionsPr.root"
#GenuineFileCorrelation: "/home/galucia/antiLithium4/analysis/output/CATS/CATS.root"
#GenuineNameCorrelation: "hHe3_p_Coul_CF_LS"
#Centralities: 
#  CentralityBinEdges: [0, 10, 30, 50]
#
## tpc calibration configuration
#InputFileTPCcalibration: "/data/galucia/lithium_local/same/LHC23_PbPb_pass4_long_same.root"
#SEFileTPCcalibration: "/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_selectionsPr.root"
#
## comparison studies
#SEFileComparison: "/home/galucia/antiLithium4/analysis/output/LHC24/data_cross_check.root"
#MEFileComparison: "/home/galucia/antiLithium4/analysis/output/LHC24/event_mixing_cross_check.root"
#
#figuresFolderPath: "/home/galucia/antiLithium4/analysis/figures/"


comparisonVariables: ["Kinematics/PtHe3",
                      "Kinematics/PtPr",
                      "TPC/NSigmaTPCHe3",
                      "TPC/NSigmaTPCPr",
                      "DCA/DCAxyHe3",
                      "DCA/DCAzHe3",
                      "DCA/DCAxyPr",
                      "DCA/DCAzPr",]
