## visualization configuration file 

## output file path
#studiesOutputFilePath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/studies_corrected.root"
#
## invariant mass configuration
#SEFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/data_visual_corrected_selectionsPr.root"
#MEFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/event_mixing_visual_corrected_selectionsPr.root"
#CorrectionFileInvMass: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/CATS/CATS.root"
#
## correlation configuration
#SEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/data_visual_corrected_selectionsPr.root"
#MEFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/event_mixing_visual_corrected_selectionsPr.root"
#GenuineFileCorrelation: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/CATS/CATS.root"
#GenuineNameCorrelation: "hHe3_p_Coul_CF_LS"
#Centralities: 
#  CentralityBinEdges: [0, 10, 30, 50]
#
#figuresFolderPath: "/Users/glucia/Projects/ALICE/antiLithium4/analysis/figures/"



## output file path
studiesOutputFilePath: "/home/galucia/antiLithium4/analysis/output/PbPb/studies.root"

# invariant mass configuration
SEFileInvMass: "/home/galucia/antiLithium4/analysis/output/PbPb/data_visual_selectionsPr.root"
MEFileInvMass: "/home/galucia/antiLithium4/analysis/output/PbPb/event_mixing_visual_selectionsPr.root"
CorrectionFileInvMass: "/home/galucia/antiLithium4/analysis/output/CATS/CATS.root"

# correlation configuration
SEFileCorrelation: "/home/galucia/antiLithium4/analysis/output/PbPb/data_visual_selectionsPr.root"
MEFileCorrelation: "/home/galucia/antiLithium4/analysis/output/PbPb/event_mixing_visual_selectionsPr.root"
GenuineFileCorrelation: "/home/galucia/antiLithium4/analysis/output/CATS/CATS.root"
GenuineNameCorrelation: "hHe3_p_Coul_CF_LS"
Centralities: 
  CentralityBinEdges: [0, 10, 30, 50]

figuresFolderPath: "/home/galucia/antiLithium4/analysis/figures/"
