inFilePath: [ '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24af_pass1_skimmed_same.root',
             '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24ag_pass1_skimmed_same.root',
             '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24aj_pass1_skimmed_same.root',
             #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24al_pass1_skimmed_same.root',
             #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC23_pass4_skimmed_same.root'
             ]
outFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual.root'
visualFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_visual.yml'

#inFilePath: ['/data/galucia/lithium_local/same/LHC24af_pass1_skimmed_same.root',
#             '/data/galucia/lithium_local/same/LHC24ag_pass1_skimmed_same.root',
#             '/data/galucia/lithium_local/same/LHC24aj_pass1_skimmed_same.root',
#             #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24al_pass1_skimmed_same.root',
#             #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC23_pass4_skimmed_same.root'
#             ]
#outFilePath: '/home/galucia/antiLithium4/analysis/output/LHC24/data_visual.root'
#visualFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_visual.yml'

antimatterOnly: True