outDirs: ["QA", "InvMass", "Kinematics", "ITS", "TPC", "TOF", "DCA", "PID", "Centrality", "Efficiency", "Correlations", "SelfCorrelations"]

# Invariant mass

InvMassMatter: {  name: "InvMassMatter",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 310,
            xMin: 3.737,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "matter",
            dir: "InvMass",
            }

InvMassAnti: {  name: "InvMassAnti",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 310,
            xMin: 3.737,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "antimatter",
            dir: "InvMass",
            }

InvMassLS: {  name: "InvMassLS",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 310,
            xMin: 3.737,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "like-sign",
            dir: "InvMass",
            }

InvMassUS: {  name: "InvMassUS",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 310,
            xMin: 3.737,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "unlike-sign",
            dir: "InvMass",
            }

InvMassPt: { name: "InvMassPt",
              title: "Self correlations ; pt; m (GeV/#it{c})",
              xVariable: "fSignedPtLi",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: -5,
              xMax: 5,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassMassT: { name: "InvMassMassT",
              title: " ; m_{T} (GeV/#it{c}^{2}); m (GeV/#it{c}^{2})",
              xVariable: "fMassT",
              yVariable: "fMassInv",
              nXBins: 310,
              xMin: 3.737,
              xMax: 4.047,
              nYBins: 310,
              yMin: 3.737,
              yMax: 4.047,
              type: "TH2F",
              particle: ["Li"],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassCentralityAnti: { name: "InvMassCentralityAnti",
              title: " ; Centrality FT0C (%); m (GeV/#it{c}^{2})",
              xVariable: "fCentralityFT0C",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 310,
              yMin: 3.737,
              yMax: 4.047,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassCentralityMatter: { name: "InvMassCentralityMatter",
              title: " ; Centrality FT0C (%); m (GeV/#it{c}^{2})",
              xVariable: "fCentralityFT0C",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 310,
              yMin: 3.737,
              yMax: 4.047,
              type: "TH2F",
              particle: [""],
              opt: "matter",
              dir: "InvMass",
            }

MassTCentralityAnti: { name: "MassTCentralityAnti",
              title: " ; Centrality FT0C (%); m (GeV/#it{c}^{2})",
              xVariable: "fCentralityFT0C",
              yVariable: "fMassTLi",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 310,
              yMin: 3.737,
              yMax: 4.047,
              type: "TH2F",
              particle: [""],
              opt: "anti-kstar0-200",
              dir: "InvMass",
            }

MassTCentralityMatter: { name: "MassTCentralityMatter",
              title: " ; Centrality FT0C (%); m (GeV/#it{c}^{2})",
              xVariable: "fCentralityFT0C",
              yVariable: "fMassTLi",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 310,
              yMin: 3.737,
              yMax: 4.047,
              type: "TH2F",
              particle: [""],
              opt: "matter-kstar0-200",
              dir: "InvMass",
            }


# Correlation studies

KstarAnti: { name: "fKstarAnti",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "antimatter",
          dir: "Correlations",
        }

KstarMatter: { name: "fKstarMatter",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "matter",
          dir: "Correlations",
        }

KstarUS: { name: "fKstarUS",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "unlike-sign",
          dir: "Correlations",
        }

KstarCentralityAnti: { name: "fKstarCentralityAnti",
              title: " ; Centrality FT0C (%); #it{k}* (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "Correlations",
            }

KstarCentralityMatter: { name: "fKstarCentralityMatter",
              title: " ; Centrality FT0C (%); #it{k}* (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "matter",
              dir: "Correlations",
            }

KstarCentralityUS: { name: "fKstarCentralityUS",
              title: " ; Centrality FT0C (%); #it{k}* (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "unlike-sign",
              dir: "Correlations",
            }

KstarMassTAnti: { name: "fKstarMassTAnti",
              title: " ; m_{T} (GeV/#it{c}^{2}); #it{k}* (GeV/#it{c})",
              xVariable: "fMassTLi",
              yVariable: "fKstar",
              nXBins: 310,
              xMin: 3.737,
              xMax: 4.047,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "antimatter-cent0-10",
              dir: "Correlations",
            }

KstarMassTMatter: { name: "fKstarMassTMatter",
              title: " ; m_{T} (GeV/#it{c}^{2}); #it{k}* (GeV/#it{c})",
              xVariable: "fMassTLi",
              yVariable: "fKstar",
              nXBins: 310,
              xMin: 3.737,
              xMax: 4.047,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "matter-cent0-10",
              dir: "Correlations",
            }

KstarMassTUS: { name: "fKstarMassTUS",
              title: " ; m_{T} (GeV/#it{c}^{2}); #it{k}* (GeV/#it{c})",
              xVariable: "fMassTLi",
              yVariable: "fKstar",
              nXBins: 310,
              xMin: 3.737,
              xMax: 4.047,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "unlike-sign-cent0-10",
              dir: "Correlations",
            }

KtCentralityAnti: { name: "fKtCentralityAnti",
              title: " ; Centrality FT0C (%); #it{k}_{T} (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKt",
              nXBins: 10,
              xMin: 0,
              xMax: 100,
              nYBins: 300,
              yMin: 0.,
              yMax: 3.,
              type: "TH2F",
              particle: [""],
              opt: "anti-kstar0-200",
              dir: "Correlations",
            }

KtCentralityMatter: { name: "fKtCentralityMatter",
              title: " ; Centrality FT0C (%); #it{k}_{T} (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKt",
              nXBins: 10,
              xMin: 0,
              xMax: 100,
              nYBins: 300,
              yMin: 0.,
              yMax: 3.,
              type: "TH2F",
              particle: [""],
              opt: "matter-kstar0-200",
              dir: "Correlations",
            }
