outDirs: ["QA", "InvMass", "Kinematics", "ITS", "TPC", "TOF", "DCA", "PID", "Centrality", "Efficiency", "Correlations", "SelfCorrelations"]

# Invariant mass

InvMassMatter: {  name: "InvMassMatter",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "matter",
            dir: "InvMass",
            }

InvMassAnti: {  name: "InvMassAnti",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "antimatter",
            dir: "InvMass",
            }

InvMassLS: {  name: "InvMassLS",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "like-sign",
            dir: "InvMass",
            }

InvMassUS: {  name: "InvMassUS",
            title: "Invariant Mass (Reconstructed); m (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassInv",
            nXBins: 300,
            xMin: 3.747,
            #xMax: 4.047,
            xMax: 4.5,
            type: "TH1F",
            particle: ["Li"],
            opt: "unlike-sign",
            dir: "InvMass",
            }

MassTMatter: {  name: "MassTMatter",
            title: "Transverse Mass (Reconstructed); m_{T} (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassT",
            nXBins: 300,
            xMin: 3.747,
            xMax: 4.047,
            type: "TH1F",
            particle: ["Li"],
            opt: "matter",
            dir: "InvMass",
            }

MassTAnti: {  name: "MassTAnti",
            title: "Transverse Mass (Reconstructed); m_{T} (GeV/#it{c}^{2}); Counts",
            xVariable: "fMassT",
            nXBins: 300,
            xMin: 3.747,
            xMax: 4.047,
            type: "TH1F",
            particle: ["Li"],
            opt: "antimatter",
            dir: "InvMass",
            }

InvMassPt: { name: "InvMassPt",
              title: "Self correlations ; pt; m (GeV/#it{c})",
              xVariable: "fSignedPtLi",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: -5,
              xMax: 5,
              nYBins: 100,
              yMin: 3.7,
              yMax: 3.9,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassMassT: { name: "InvMassMassT",
              title: " ; m_{T} (GeV/#it{c}^{2}); m (GeV/#it{c}^{2})",
              xVariable: "fMassT",
              yVariable: "fMassInv",
              nXBins: 300,
              xMin: 3.747,
              xMax: 4.047,
              nYBins: 300,
              yMin: 3.747,
              yMax: 4.047,
              type: "TH2F",
              particle: ["Li"],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassCentralityAnti: { name: "InvMassCentralityAnti",
              title: " ; Centrality FT0C (%); m (GeV/#it{c}^{2})",
              xVariable: "fCentralityFT0C",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 300,
              yMin: 3.747,
              yMax: 4.047,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "InvMass",
            }

InvMassCentralityMatter: { name: "InvMassCentralityMatter",
              title: " ; Centrality FT0C (%); m (GeV/#it{c}^{2})",
              xVariable: "fCentralityFT0C",
              yVariable: "fMassInvLi",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 300,
              yMin: 3.747,
              yMax: 4.047,
              type: "TH2F",
              particle: [""],
              opt: "matter",
              dir: "InvMass",
            }


# Kinematics

PtMatter: { name: "PtMatter",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Had", "Li"],
      opt: "matter",
      dir: "Kinematics",
      }

PtAnti: { name: "PtAnti",
      title: "p_{T} Distribution (Reconstructed); p_{T} (GeV/#it{c}); Counts",
      xVariable: "fSignedPt",
      selection: "",
      nXBins: 200,
      xMin: -10,
      xMax: 10,
      type: "TH1F",
      particle: ["He3", "Had", "Li"],
      opt: "antimatter",
      dir: "Kinematics",
      }

Eta: { name: "Eta",
        title: "#eta Distribution (Reconstructed); #eta; Counts",
        xVariable: "fEta",
        selection: "",
        nXBins: 100,
        xMin: -1,
        xMax: 1,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "Kinematics",
      }

Phi: { name: "Phi",
        title: "#phi Distribution (Reconstructed); #phi; Counts",
        xVariable: "fPhi",
        selection: "",
        nXBins: 100,
        xMin: -3.14,
        xMax: 3.14,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "Kinematics",
      }

DCAxy: { name: "DCAxy",
        title: "DCAxy Distribution (Reconstructed); DCAxy [cm]; Counts",
        xVariable: "fDCAxy",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "DCA",
      }

DCAz: { name: "DCAz",
        title: "DCAz Distribution (Reconstructed); DCAz [cm]; Counts",
        xVariable: "fDCAz",
        selection: "",
        nXBins: 100,
        xMin: -0.2,
        xMax: 0.2,
        type: "TH1F",
        particle: ["He3", "Had"],
        opt: "antimatter",
        dir: "DCA",
      }

# ITS

ClusterSizevsPSigned: { name: "ClusterSizevsPSigned",
          title: "; signed #it{p}^{reco}_{T} (GeV/#it{c}); #LT ITS Cluster Size #GT #times #LT cos#lambda #GT",
          xVariable: "fSignedPt",
          yVariable: "fClSizeITSCosLam",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 120,
          yMin: 0,
          yMax: 15,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "ITS",
        }

NSigmaITSvsPt: { name: "NSigmaITSvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{ITS}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaITS",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "ITS",
        } 

# TPC

NSigmaTPCvsPt: { name: "NSigmaTPCvsPt",
          title: "NSigmaTPC (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TPC}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTPC",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 100,
          yMin: -5,
          yMax: 5,
          type: "TH2F",
          particle: ["He3", "Had"],
          opt: "antimatter",
          dir: "TPC",
        } 

# TOF

NSigmaTOFvsPt: { name: "NSigmaTOFvsPt",
          title: "NSigmaTOF (Reconstructed); signed #it{p}_{T} (GeV/#it{c}); n#sigma_{TOF}",
          xVariable: "fSignedPt",
          yVariable: "fNSigmaTOF",
          nXBins: 100,
          xMin: -5,
          xMax: 5,
          nYBins: 200,
          yMin: -10,
          yMax: 10,
          type: "TH2F",
          particle: ["Had"],
          opt: "antimatter",
          dir: "TOF",
        }

# Centrality

CentralityFT0C: { name: "CentralityFT0C",
      title: "; Centrality FT0C (%); Counts",
      xVariable: "fCentralityFT0C",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 100,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

MultiplicityFT0C: { name: "MultiplicityFT0C",
      title: "; Multiplicity FT0C; Counts",
      xVariable: "fMultiplicityFT0C",
      selection: "",
      nXBins: 100,
      xMin: 0,
      xMax: 70000,
      type: "TH1F",
      particle: [""],
      opt: "full",
      dir: "Centrality",
      }

# Correlation studies

DeltaEtaDeltaPhi: { name: "DeltaEtaDeltaPhi",
              title: "; #Delta#eta; #Delta#phi",
              xVariable: "fDeltaEta",
              yVariable: "fDeltaPhi",
              nXBins: 50,
              xMin: -0.15,
              xMax: 0.15,
              nYBins: 50,
              yMin: -0.15,
              yMax: 0.15,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "Correlations",
            }

KstarAnti: { name: "fKstarAnti",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "antimatter",
          dir: "Correlations",
        }

KstarMatter: { name: "fKstarMatter",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "matter",
          dir: "Correlations",
        }

KstarUS: { name: "fKstarUS",
          title: "; #it{k}* (GeV/#it{c}); Counts",
          xVariable: "fKstar",
          nXBins: 400,
          xMin: 0.,
          xMax: 2.,
          type: "TH1F",
          particle: [""],
          opt: "unlike-sign",
          dir: "Correlations",
        }

KstarCentralityAnti: { name: "fKstarCentralityAnti",
              title: " ; Centrality FT0C (%); #it{k}* (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "antimatter",
              dir: "Correlations",
            }

KstarCentralityMatter: { name: "fKstarCentralityMatter",
              title: " ; Centrality FT0C (%); #it{k}* (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "matter",
              dir: "Correlations",
            }

KtstarCentrality: { name: "fKtstarCentrality",
              title: " ; Centrality FT0C (%); #it{k}*_{T} (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKtstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "full",
              dir: "Correlations",
            }

KstarCentralityUS: { name: "fKstarCentralityUS",
              title: " ; Centrality FT0C (%); #it{k}* (GeV/#it{c})",
              xVariable: "fCentralityFT0C",
              yVariable: "fKstar",
              nXBins: 100,
              xMin: 0,
              xMax: 100,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "unlike-sign",
              dir: "Correlations",
            }

KstarMassTAnti: { name: "fKstarMassTAnti",
              title: " ; m_{T} (GeV/#it{c}^{2}); #it{k}* (GeV/#it{c})",
              xVariable: "fMassTLi",
              yVariable: "fKstar",
              nXBins: 300,
              xMin: 3.747,
              xMax: 4.047,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "antimatter-cent0-10",
              dir: "Correlations",
            }

KstarMassTMatter: { name: "fKstarMassTMatter",
              title: " ; m_{T} (GeV/#it{c}^{2}); #it{k}* (GeV/#it{c})",
              xVariable: "fMassTLi",
              yVariable: "fKstar",
              nXBins: 300,
              xMin: 3.747,
              xMax: 4.047,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "matter-cent0-10",
              dir: "Correlations",
            }

KstarMassTUS: { name: "fKstarMassTUS",
              title: " ; m_{T} (GeV/#it{c}^{2}); #it{k}* (GeV/#it{c})",
              xVariable: "fMassTLi",
              yVariable: "fKstar",
              nXBins: 300,
              xMin: 3.747,
              xMax: 4.047,
              nYBins: 400,
              yMin: 0.,
              yMax: 2.,
              type: "TH2F",
              particle: [""],
              opt: "unlike-sign-cent0-10",
              dir: "Correlations",
            }
