inFilePath: ['/Users/glucia/Projects/ALICE/data/lithium/mixing/LHC24af_pass1_skimmed_mixing.root',
             '/Users/glucia/Projects/ALICE/data/lithium/mixing/LHC24ag_pass1_skimmed_mixing.root',
             '/Users/glucia/Projects/ALICE/data/lithium/mixing/LHC24aj_pass1_skimmed_mixing.root',
             '/Users/glucia/Projects/ALICE/data/lithium/mixing/LHC24al_pass1_skimmed_mixing.root',
             #'/Users/glucia/Projects/ALICE/data/lithium/mixing/LHC23_pass4_skimmed_mixing.root'
             ]
outFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/event_mixing_visual.root'
visualFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_visual.yml'

#inFilePath: ['/data/galucia/lithium_local/mixing/LHC24af_pass1_skimmed_mixing.root',
#             '/data/galucia/lithium_local/mixing/LHC24ag_pass1_skimmed_mixing.root',
#             '/data/galucia/lithium_local/mixing/LHC24aj_pass1_skimmed_mixing.root',
#             '/data/galucia/lithium_local/mixing/LHC24al_pass1_skimmed_mixing.root',
#             #'/Users/glucia/Projects/ALICE/data/lithium/mixing/LHC23_pass4_skimmed_mixing.root'
#             ]
#outFilePath: '/home/galucia/antiLithium4/analysis/output/LHC24/event_mixing_visual.root'
#visualFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_visual.yml'

antimatterOnly: True