#inFilePath: [ # pp
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24af_pass1_skimmed_same.root',
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24ag_pass1_skimmed_same.root',
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24aj_pass1_skimmed_same.root',
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24al_pass1_skimmed_same.root',
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24am_pass1_skimmed_same.root',
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24an_pass1_skimmed_same.root',
#              #'/Users/glucia/Projects/ALICE/data/lithium/same/LHC24ao_pass1_skimmed_same.root',
#              # pbpb
#              '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24ar_pass1_same.root',
#              '/Users/glucia/Projects/ALICE/data/lithium/same/LHC24as_pass1_same.root',
#             ]
#outFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/data_visual_corrected.root'
#             #'/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/data_visual.root'
#visualFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_visual.yml'
#outQaFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24PbPb/qa_us.root'
#               #'/Users/glucia/Projects/ALICE/antiLithium4/analysis/output/LHC24/qa_us.root'
#qaFilePath: '/Users/glucia/Projects/ALICE/antiLithium4/analysis/config/cfg_qa.yml'

inFilePath: [ #'/data/galucia/lithium_local/same/LHC24af_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24ag_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24aj_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24al_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24am_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC24an_pass1_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC23_pass4_skimmed_same.root',
              #'/data/galucia/lithium_local/same/LHC23zzh_pass4_small_same.root',
              #'/data/galucia/lithium_local/same/LHC23_PbPb_pass4_long_same_lsus.root',
              #'/data/galucia/lithium_local/same/LHC23_PbPb_pass4_long_same_us.root',
              '/data/galucia/lithium_local/same/LHC24ar_pass1_same.root',
              '/data/galucia/lithium_local/same/LHC24as_pass1_same.root',
              #'/home/galucia/antiLithium4/task/MCWorkflowAnalysis/LHC24af_same.root'
             ]

outFilePath: #'/home/galucia/antiLithium4/analysis/output/LHC24/data_visual.root'
             #'/home/galucia/antiLithium4/analysis/output/LHC23zzh/data_visual.root'
             #'/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_new.root'
             #'/home/galucia/antiLithium4/analysis/output/LHC23PbPb/data_visual_us.root'
             '/home/galucia/antiLithium4/analysis/output/LHC24PbPb/data_visual.root'
             #'/home/galucia/antiLithium4/analysis/output/LHC24/data_cross_check.root'
outQaFilePath: #'/home/galucia/antiLithium4/analysis/output/LHC23PbPb/qa.root'
               '/home/galucia/antiLithium4/analysis/output/LHC24PbPb/qa.root'

visualFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_visual.yml'
qaFilePath: '/home/galucia/antiLithium4/analysis/config/cfg_qa.yml'

treeNames: [ 'O2he3hadtable', 'O2he3hadmult' ]
#treeNames: [ 'fTreeLRC' ]
folderName: 'DF*'
antimatterOnly: True

selections: [
  'fDeltaEta: (fDeltaPhi/0.006)**2 + (fDeltaEta/0.006)**2 > 1',

  'fEtaHe3: -0.9 < fEtaHe3 < 0.9',
  #'fPIDtrkHe3: fPIDtrkHe3 == 7',
  'fPIDtrkHe3: fPtHe3 < 2.5 or fPIDtrkHe3 == 7',
  #'fPtHe3: abs(fPtHe3) > 1.6',
  'fChi2TPCHe3: 0.5 < fChi2TPCHe3 < 4',
  #'fChi2TPCHe3: fChi2TPCHe3 < 4',
  #'fNSigmaTPCHe3: -2 < fNSigmaTPCHe3 < 2',
  #'fNSigmaTPCHe3: -0.9 < fNSigmaTPCHe3 < 1.9',  # 2023
  
  # 2024: (mu - 2 sigma) < x < (mu + 2 sigma)
  'fNSigmaTPCHe3: (1.7 - 0.86*fPtHe3 + 0.11*fPtHe3*fPtHe3 - 2*(0.43 + 0.06*fPtHe3)) < fNSigmaTPCHe3 < (1.7 - 0.86*fPtHe3 + 0.11*fPtHe3*fPtHe3 + 2*(0.43 + 0.06*fPtHe3))',
  'fDCAxyHe3: abs(fDCAxyHe3) < 0.1',
  'fDCAzHe3: abs(fDCAzHe3) < 1.0',
  'fNSigmaITSHe3: fNSigmaITSHe3 > -1.5',

  'fEtaHad: -0.9 < fEtaHad < 0.9',
  'fChi2TPCHad: 0.5 < fChi2TPCHad < 4',
  #'fChi2TPCHad: fChi2TPCHad < 4',
  'fNSigmaTPCHad: abs(fNSigmaTPCHad) < 2',
  'fNSigmaTOFHad: (fPtHad < 0.8) or (-2 < fNSigmaTOFHad < 2)',
  'fNSigmaITSHad: fNSigmaITSHad > -1.5',
]